#!/bin/bash

readonly TITLE="Mot de passe"

cd $(dirname $(readlink -f $0))

. functions/base.sh

. adapters/android/adb-shell.sh
. adapters/android/adb-shell-input.sh
. adapters/android/termux-dialog.sh
. adapters/firefox.sh
. adapters/openssl.sh
. adapters/vault.sh
. adapters/x11/xdotool.sh
. adapters/x11/zenity.sh

set -e

site="${1:-}"

choose site "Sélectionnez le site" "$(web_site)" <(list)
ask site "Nom du site" "$(web_site)"
load "$site"

ask iterations "Nombre d'itérations" $(iterations "$site")
ask length "Longueur" none
ask filter "Filtre" "s/[^0-9a-zA-Z]//g"
secret pass "Mot de passe"

type_password "$(
  password "${site}" "${pass}" "${iterations}" \
    | filter "${filter}" "${length}"
)"

save "$site"
